apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wakeonlan-webapp
  namespace: wakeonlan-webapp
  annotations:
    # 必要に応じて ingress-class や cert-manager の設定を追加してください
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: wol.local.yhiraki.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wakeonlan-webapp
            port:
              number: 80
